name: CI
on:
  push:
    branches: [ master ]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: publish # will run `yarn publish` command
